package online.syncio.view;

import online.syncio.component.MyTextPane;

public class CommentUI extends javax.swing.JPanel {

    public CommentUI(String username, String cmt, String date) {
        initComponents();        
        
        lblComment.setText("<html><body style=\"font-family:'sans-serif'\"><p style=\"width:190px\"><b>" + username + "</b>   " + cmt + "</p><span font color='gray' style=\"font-size:8px\">" + date + "</span></body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComment = new online.syncio.component.MyLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(276, 55));
        setPreferredSize(new java.awt.Dimension(276, 55));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lblComment.setBackground(new java.awt.Color(255, 255, 255));
        lblComment.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        lblComment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/profile_24px.png"))); // NOI18N
        lblComment.setText("<html><b>56duong</b> comment<br><span style='font-size:8px'>2022-02-02 02:02:02</span></html>");
        lblComment.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblComment.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblComment.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(lblComment);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private online.syncio.component.MyLabel lblComment;
    // End of variables declaration//GEN-END:variables
}
