package online.syncio.component;

import java.awt.Color;

public class MyDialog extends javax.swing.JPanel {

    /**
     * Creates new form MyDIalog2
     */
    public MyDialog(String title, String text) {
        initComponents();
        
        //rounded frame
        setBackground(new Color(0f, 0f, 0f, 0f));
        setSize(350, 170);
        
        lblTitle.setText(title);
        lblText.setText("<html><p style='text-align: center;'>" + text + "</p></html>");
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new online.syncio.component.MyPanel();
        pnlTop = new online.syncio.component.MyPanel();
        btnClose = new online.syncio.component.MyButton();
        pnlCenter = new online.syncio.component.MyPanel();
        lblTitle = new online.syncio.component.MyLabel();
        lblText = new online.syncio.component.MyLabel();
        pnlBottom = new online.syncio.component.MyPanel();
        btnDismiss = new online.syncio.component.MyButton();

        setLayout(new java.awt.BorderLayout());

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setBorderColor(new java.awt.Color(219, 219, 219));
        pnlMain.setBorderThickness(1);
        pnlMain.setRoundBottomLeft(10);
        pnlMain.setRoundBottomRight(10);
        pnlMain.setRoundTopLeft(10);
        pnlMain.setRoundTopRight(10);
        pnlMain.setLayout(new javax.swing.BoxLayout(pnlMain, javax.swing.BoxLayout.Y_AXIS));

        pnlTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop.setMaximumSize(new java.awt.Dimension(350, 30));
        pnlTop.setMinimumSize(new java.awt.Dimension(350, 30));
        pnlTop.setPreferredSize(new java.awt.Dimension(350, 30));

        btnClose.setBackground(null);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/close_16px.png"))); // NOI18N
        btnClose.setBorderThickness(0);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMain.add(pnlTop);

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCenter.setAlignmentX(0.5F);
        pnlCenter.setLayout(new javax.swing.BoxLayout(pnlCenter, javax.swing.BoxLayout.Y_AXIS));

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Unsaved changes");
        lblTitle.setFont(new java.awt.Font("SF Pro Display Regular", 0, 18)); // NOI18N
        lblTitle.setMaximumSize(new java.awt.Dimension(350, 30));
        lblTitle.setMinimumSize(new java.awt.Dimension(350, 30));
        lblTitle.setName("lblTitle"); // NOI18N
        lblTitle.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlCenter.add(lblTitle);

        lblText.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        lblText.setForeground(new java.awt.Color(115, 115, 115));
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("<html><p style='text-align: center;'>You have unsaved changes. Are you sure you want to cancel?</p></html>");
        lblText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblText.setFont(lblText.getFont().deriveFont(lblText.getFont().getStyle() & ~java.awt.Font.BOLD));
        lblText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblText.setMaximumSize(new java.awt.Dimension(350, 23122));
        lblText.setMinimumSize(new java.awt.Dimension(54, 50));
        lblText.setName("lblText"); // NOI18N
        pnlCenter.add(lblText);

        pnlMain.add(pnlCenter);

        pnlBottom.setBackground(new java.awt.Color(255, 255, 255));
        pnlBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 0, 0));
        pnlBottom.setMaximumSize(new java.awt.Dimension(350, 50));
        pnlBottom.setMinimumSize(new java.awt.Dimension(350, 50));
        pnlBottom.setPreferredSize(new java.awt.Dimension(350, 50));
        pnlBottom.setLayout(new java.awt.BorderLayout());

        btnDismiss.setBackground(null);
        btnDismiss.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(219, 219, 219)));
        btnDismiss.setForeground(new java.awt.Color(0, 149, 246));
        btnDismiss.setText("Dismiss");
        btnDismiss.setBorderThickness(0);
        btnDismiss.setFontBold(2);
        btnDismiss.setName("btnDismiss"); // NOI18N
        btnDismiss.setRadius(20);
        btnDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDismissActionPerformed(evt);
            }
        });
        pnlBottom.add(btnDismiss, java.awt.BorderLayout.CENTER);

        pnlMain.add(pnlBottom);

        add(pnlMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        GlassPanePopup.closePopup("dialog");
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDismissActionPerformed
        GlassPanePopup.closePopup("dialog");
    }//GEN-LAST:event_btnDismissActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private online.syncio.component.MyButton btnClose;
    private online.syncio.component.MyButton btnDismiss;
    private online.syncio.component.MyLabel lblText;
    private online.syncio.component.MyLabel lblTitle;
    private online.syncio.component.MyPanel pnlBottom;
    private online.syncio.component.MyPanel pnlCenter;
    private online.syncio.component.MyPanel pnlMain;
    private online.syncio.component.MyPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
