package online.syncio.component;

import java.awt.Color;
import online.syncio.model.MyFont;

public class MyDialog extends javax.swing.JPanel {

    /**
     * Creates new form MyDIalog2
     */
    public MyDialog(String title, String text) {
        initComponents();
        
        //rounded frame
        setBackground(new Color(0f, 0f, 0f, 0f));
        setSize(350, 170);
        
        btnDismiss.setFont(new MyFont().SFProDisplayBold);
        
        lblTitle.setText(title);
        lblText.setText("<html><p style='text-align: center;'>" + text + "</p></html>");
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new online.syncio.component.MyPanel();
        btnClose = new online.syncio.component.MyButton();
        lblTitle = new online.syncio.component.MyLabel();
        lblText = new online.syncio.component.MyLabel();
        btnDismiss = new online.syncio.component.MyButton();

        setLayout(new java.awt.BorderLayout());

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));
        pnlMain.setBorderThickness(1);

        btnClose.setBackground(null);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/close_16px.png"))); // NOI18N
        btnClose.setBorderThickness(0);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Unsaved changes");
        lblTitle.setFont(new java.awt.Font("SF Pro Display Regular", 0, 18)); // NOI18N

        lblText.setForeground(new java.awt.Color(115, 115, 115));
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("<html><p style='text-align: center;'>You have unsaved changes. Are you sure you want to cancel?</p></html>");
        lblText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblText.setFont(lblText.getFont().deriveFont(lblText.getFont().getStyle() & ~java.awt.Font.BOLD));

        btnDismiss.setBackground(null);
        btnDismiss.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(219, 219, 219)));
        btnDismiss.setForeground(new java.awt.Color(0, 149, 246));
        btnDismiss.setText("Dismiss");
        btnDismiss.setBorderThickness(0);
        btnDismiss.setRadius(20);
        btnDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDismissActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(btnDismiss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnDismiss, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        add(pnlMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        GlassPanePopup.closePopup("dialog");
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDismissActionPerformed
        GlassPanePopup.closePopup("dialog");
    }//GEN-LAST:event_btnDismissActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private online.syncio.component.MyButton btnClose;
    private online.syncio.component.MyButton btnDismiss;
    private online.syncio.component.MyLabel lblText;
    private online.syncio.component.MyLabel lblTitle;
    private online.syncio.component.MyPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
