package online.syncio;
// Test pull

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import online.syncio.model.MyFont;
import online.syncio.ui.PopupCreateNewPost;
import online.syncio.component.GlassPanePopup;

public class Main extends javax.swing.JFrame {

    static JButton[] btnMenuList;
    public static String prevTab, curTab;
    public static MyFont myFont = new MyFont();

    public Main() {
        setUndecorated(true);
        initComponents();
        GlassPanePopup.install(this);
        setBackground(new Color(0f, 0f, 0f, 0f));
        setLocationRelativeTo(null);

        // tab
        pnlTabContent.setLayout(new CardLayout());
        pnlTabContent.add(new Home(), "home");
        pnlTabContent.add(new Search(), "search");
        pnlTabContent.add(new Message(), "messages");
        pnlTabContent.add(new Notification(), "notifications");
        pnlTabContent.add(new Profile(), "profile");

        btnMenuList = new JButton[]{btnHome, btnSearch, btnMessage, btnNotification, btnCreate, btnProfile};

        for (JButton btn : btnMenuList) {
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    JButton btn = (JButton) e.getSource();
     
                    String name = e.getActionCommand().toLowerCase().replaceAll(" ", "");
                    
                    // show tab
                    showTab(name, btn);
                }
            });
        }
    }

    /**
     * Shows the specified tab.
     *
     * @param newTab The name of the tab to be shown.
     */
    public static void showTab(String newTab) {
        for (JButton b : btnMenuList) {
            if (b.getText().trim().equalsIgnoreCase(curTab)) {
                b.setFont(myFont.SFProDisplayMedium);
                b.setFont(b.getFont().deriveFont(16f));
                break;
            }
            
            if(b.getText().trim().equalsIgnoreCase(newTab)) {
                b.setFont(myFont.SFProDisplayBold);
                b.setFont(b.getFont().deriveFont(16f));
            }
        }
  
        prevTab = curTab;
        curTab = newTab;
        
        if(!newTab.equals("create")) {
            CardLayout c = (CardLayout) pnlTabContent.getLayout();
            c.show(pnlTabContent, curTab);
        }
    }
    
    public static void showTab(String newTab, JButton btn) {
        btn.setFont(myFont.SFProDisplayBold);
        btn.setFont(btn.getFont().deriveFont(16f));

        for (JButton b : btnMenuList) {
            if (b.getText().trim().equalsIgnoreCase(curTab)) {
                b.setFont(myFont.SFProDisplayMedium);
                b.setFont(b.getFont().deriveFont(16f));
                break;
            }
        }
  
        prevTab = curTab;
        curTab = newTab;
        
        if(!newTab.equals("create")) {
            CardLayout c = (CardLayout) pnlTabContent.getLayout();
            c.show(pnlTabContent, curTab);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new online.syncio.component.MyPanel();
        pnlTitleBar = new online.syncio.component.WindowTitleBar();
        pnlLeftMenu = new online.syncio.component.MyPanel();
        btnHome = new online.syncio.component.MyButton();
        btnSearch = new online.syncio.component.MyButton();
        btnMessage = new online.syncio.component.MyButton();
        btnNotification = new online.syncio.component.MyButton();
        btnCreate = new online.syncio.component.MyButton();
        btnProfile = new online.syncio.component.MyButton();
        pnlTabContent = new online.syncio.component.MyPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlMain.setBackground(null);
        pnlMain.setRadius(20);
        pnlMain.setRoundBottomLeft(20);
        pnlMain.setRoundBottomRight(20);
        pnlMain.setRoundTopLeft(20);
        pnlMain.setRoundTopRight(20);
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlTitleBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(219, 219, 219)));
        pnlTitleBar.setFrame(this);
        pnlMain.add(pnlTitleBar, java.awt.BorderLayout.PAGE_START);

        pnlLeftMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeftMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(219, 219, 219)));
        pnlLeftMenu.setMaximumSize(new java.awt.Dimension(200, 679));
        pnlLeftMenu.setMinimumSize(new java.awt.Dimension(200, 679));
        pnlLeftMenu.setPreferredSize(new java.awt.Dimension(200, 679));
        pnlLeftMenu.setRoundBottomLeft(20);
        pnlLeftMenu.setLayout(new javax.swing.BoxLayout(pnlLeftMenu, javax.swing.BoxLayout.Y_AXIS));

        btnHome.setBackground(null);
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 15, 5, 0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/home_28px.png"))); // NOI18N
        btnHome.setText(" Home");
        btnHome.setBorderThickness(0);
        btnHome.setFont(new java.awt.Font("SF Pro Display Regular", 0, 16)); // NOI18N
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setMaximumSize(new java.awt.Dimension(200, 60));
        btnHome.setMinimumSize(new java.awt.Dimension(200, 60));
        btnHome.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlLeftMenu.add(btnHome);

        btnSearch.setBackground(null);
        btnSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 5, 0));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/search_28px.png"))); // NOI18N
        btnSearch.setText(" Search");
        btnSearch.setBorderThickness(0);
        btnSearch.setFont(new java.awt.Font("SF Pro Display Regular", 0, 16)); // NOI18N
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSearch.setMaximumSize(new java.awt.Dimension(200, 50));
        btnSearch.setMinimumSize(new java.awt.Dimension(200, 50));
        btnSearch.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlLeftMenu.add(btnSearch);

        btnMessage.setBackground(null);
        btnMessage.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 5, 0));
        btnMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/message_28px.png"))); // NOI18N
        btnMessage.setText(" Messages");
        btnMessage.setBorderThickness(0);
        btnMessage.setFont(new java.awt.Font("SF Pro Display Regular", 0, 16)); // NOI18N
        btnMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMessage.setMaximumSize(new java.awt.Dimension(200, 50));
        btnMessage.setMinimumSize(new java.awt.Dimension(200, 50));
        btnMessage.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlLeftMenu.add(btnMessage);

        btnNotification.setBackground(null);
        btnNotification.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 5, 0));
        btnNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/notification_28px.png"))); // NOI18N
        btnNotification.setText(" Notifications");
        btnNotification.setBorderThickness(0);
        btnNotification.setFont(new java.awt.Font("SF Pro Display Regular", 0, 16)); // NOI18N
        btnNotification.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNotification.setMaximumSize(new java.awt.Dimension(200, 50));
        btnNotification.setMinimumSize(new java.awt.Dimension(200, 50));
        btnNotification.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlLeftMenu.add(btnNotification);

        btnCreate.setBackground(null);
        btnCreate.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 5, 0));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/create_28px.png"))); // NOI18N
        btnCreate.setText(" Create");
        btnCreate.setBorderThickness(0);
        btnCreate.setFont(new java.awt.Font("SF Pro Display Regular", 0, 16)); // NOI18N
        btnCreate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreate.setMaximumSize(new java.awt.Dimension(200, 50));
        btnCreate.setMinimumSize(new java.awt.Dimension(200, 50));
        btnCreate.setPreferredSize(new java.awt.Dimension(200, 50));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        pnlLeftMenu.add(btnCreate);

        btnProfile.setBackground(null);
        btnProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 5, 0));
        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/profile_28px.png"))); // NOI18N
        btnProfile.setText(" Profile");
        btnProfile.setBorderThickness(0);
        btnProfile.setFont(new java.awt.Font("SF Pro Display Regular", 0, 16)); // NOI18N
        btnProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProfile.setMaximumSize(new java.awt.Dimension(200, 50));
        btnProfile.setMinimumSize(new java.awt.Dimension(200, 50));
        btnProfile.setPreferredSize(new java.awt.Dimension(200, 50));
        pnlLeftMenu.add(btnProfile);

        pnlMain.add(pnlLeftMenu, java.awt.BorderLayout.LINE_START);

        pnlTabContent.setBackground(null);
        pnlTabContent.setRoundBottomRight(20);
        pnlTabContent.setLayout(new java.awt.CardLayout());
        pnlMain.add(pnlTabContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnHome.doClick();
    }//GEN-LAST:event_formWindowOpened

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        GlassPanePopup.showPopup(new PopupCreateNewPost(), "createnewpost");
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private online.syncio.component.MyButton btnCreate;
    private online.syncio.component.MyButton btnHome;
    private online.syncio.component.MyButton btnMessage;
    private online.syncio.component.MyButton btnNotification;
    private online.syncio.component.MyButton btnProfile;
    private online.syncio.component.MyButton btnSearch;
    private online.syncio.component.MyPanel pnlLeftMenu;
    private online.syncio.component.MyPanel pnlMain;
    private static online.syncio.component.MyPanel pnlTabContent;
    private online.syncio.component.WindowTitleBar pnlTitleBar;
    // End of variables declaration//GEN-END:variables
}
