package online.syncio.view.user;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

public class CommentUI1 extends javax.swing.JPanel {

    public CommentUI1(String username, String cmt, String date) {
        initComponents();        
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/online/syncio/resources/images/icons/profile_24px.png"));  
        txtComment.appendIcon(icon);
        txtComment.appendBoldText(" " + username + " ");
        txtComment.appendTextWithEmojis(cmt);
        txtComment.appendColoredText("\n" + date, Color.GRAY, 10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtComment = new online.syncio.component.MyTextPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(276, 2147483647));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        txtComment.setBackground(new java.awt.Color(255, 204, 204));
        txtComment.setBorder(null);
        txtComment.setBorderThickness(0);
        txtComment.setMaximumSize(new java.awt.Dimension(276, 2147483647));
        add(txtComment);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private online.syncio.component.MyTextPane txtComment;
    // End of variables declaration//GEN-END:variables
}
