package online.syncio.view.user;

/**
 * Panel for displaying detailed error information to the user.
 */
public class ErrorDetail extends javax.swing.JPanel {

    /**
     * Creates a new instance of the ErrorDetail panel with the provided error information.
     *
     * @param errorInfo The detailed error information to be displayed.
     */
    public ErrorDetail(String errorInfo) {
        initComponents();
        lblErrorMes.setText("<html><body style=\"font-family:'sans-serif'\"><p style=\"width:190px\">Có lỗi xảy ra. Vui lòng thử lại sau ít phút!</body></html>");
        lblErrorInfo.setText("<html><body style=\"font-family:'sans-serif'\"><p style=\"width:190px\">Thông tin lỗi: <br>" + errorInfo + "</body></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblErrorMes = new online.syncio.component.MyLabel();
        lblErrorInfo = new online.syncio.component.MyLabel();

        setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(300, 54));
        setMinimumSize(new java.awt.Dimension(300, 54));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(300, 54));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lblErrorMes.setText("Có lỗi xảy ra. Vui lòng thử lại sau ít phút!");
        lblErrorMes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblErrorMes);

        lblErrorInfo.setText("Thông tin lỗi:");
        add(lblErrorInfo);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private online.syncio.component.MyLabel lblErrorInfo;
    private online.syncio.component.MyLabel lblErrorMes;
    // End of variables declaration//GEN-END:variables
}
